# Generated by Django 5.2.7 on 2025-10-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Movimentacao',
        ),
    ]
