# Generated by Django 5.2.7 on 2025-11-14 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Cep',
        ),
    ]
