# Generated by Django 5.2.7 on 2025-12-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_rename_perfil_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('disponível', 'Disponível'), ('em uso', 'Em uso'), ('manutenção', 'Manutenção'), ('excluído', 'Excluído')], default='disponível', max_length=20),
        ),
    ]
